name: 🐞 Bug Report
description: Report something that's not working the way it's intended.
labels: ['bug']
assignees:
  - '0Xsolcreator'
title: '🐞 [BUG] '
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue you are facing with steps to reproduce.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: Add a possible solution to the bug.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks 🙏 for reporting a bug!
