name: 💡 Feature Request
description: Request a new feature or enhancement.
labels: ['feature']
assignees:
  - '0Xsolcreator'
title: '💡 [FEATURE] '
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks 🙏 for creating a feature request!
