name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Dev-Server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Get .env from S3
        run: aws s3 cp s3://sola-secrets/.env .env

      - name: Install Dependencies with Cache
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build with Increased Memory
        run: NODE_OPTIONS="--max-old-space-size=8192" yarn build

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://sola-frontend/ \
            --exclude "*" --include "*.br" \
            --content-encoding br --cache-control max-age=60 \
            --metadata-directive REPLACE
          aws s3 sync dist/ s3://sola-frontend/ \
            --exclude "*" --include "*.gz" \
            --content-encoding gzip --cache-control max-age=60 \
            --metadata-directive REPLACE
          aws s3 sync dist/ s3://sola-frontend/ \
            --exclude "*.br" --exclude "*.gz" \
            --cache-control max-age=60

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id EWH631DYZXDBA --paths "/*"
